### ISSUE TITLE
Regression in save management

### ISSUE THREAD

**Issue by tag2015** [scemino/scummvm#14] opened 2024-03-15 12:02 UTC
After the latest (speed improvement) in the save handling, there seems to be some new issues:
After playing a bit (and triggering some autosaves) ScummVM is no longer able to save (even manually) and you get an error message related to the timestamps file
WARNING: DefaultSaveFileManager: failed to open 'timestamps' file to load timestamps!
WARNING: DefaultSaveFileManager: failed to open 'C:\Users\tag20\AppData\Roaming\ScummVM\Saved games\timestamps' file to save timestamps!
(see also attached file)
Also, if you attempt to load, the entire list is blank. To solve the issue you need to quit scummvm completely.
The issue occasionally occurred 
in the past, but now it's much more frequent.

![Capture](https://github.com/scemino/scummvm/assets/1673892/f4e66139-054f-40e2-9be9-4a8a35a9f902)

**Comment by scemino** [comment] 2024-03-17 20:31
I can't reproduce... yet.

**Comment by tag2015** [comment] 2024-03-18 14:32
I started a new playthrough with a savedir clear of saves, and I can't reproduce the issue now. I think this may occur if 1) there is a significant number of saves, let's say 20 or more or 2) there are empty save slots (e.g. the user saved in slots 1,2,3,5,10)
I'l test some more

**Comment by scemino** [comment] 2024-03-24 07:58
I close this issue then.

**Closed as completed by scemino** 2024-03-24 07:58 UTC
